project_id = "odessay"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true

[db.seed]
enabled = false

[auth.rate_limit]
sign_in_sign_ups = 1000
token_refresh = 1000
token_verifications = 1000
