import { readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, it } from "vitest"

import {
  MARK_PALETTES,
  MARK_PATHS,
  MARK_STROKE_WIDTH,
  MARK_VIEWBOX,
  bladesForSize,
  wordmarkTracking
} from "@/lib/brand/mark-geometry"

const root = process.cwd()
const brandDir = join(root, "public/brand")

function readBrandAsset(name: string) {
  return readFileSync(join(brandDir, name), "utf8")
}

/**
 * The mark is a brand contract, not a component detail. These assertions exist
 * because `docs/design/brand.md` warns that the 0 / 0.4 / 0.8 offsets look like
 * noise and are load-bearing: without them the blades fuse at small sizes.
 */
describe("brand mark geometry", () => {
  it("keeps the exact path coordinates from docs/design/brand.md", () => {
    expect(MARK_PATHS.A).toBe("M10.86 49 L31.76 14.8 L38.72 26.2 Z")
    expect(MARK_PATHS.B).toBe("M11.1 49.4 L38.97 26.6 L45.93 38 Z")
    expect(MARK_PATHS.C).toBe("M11.34 49.8 L46.18 38.4 L53.14 49.8 Z")
  })

  it("preserves the three staggered offsets that keep the hairline", () => {
    const startY = (["A", "B", "C"] as const).map((key) =>
      Number(MARK_PATHS[key].split(" ")[1])
    )
    expect(startY).toEqual([49, 49.4, 49.8])

    const startX = (["A", "B", "C"] as const).map((key) =>
      Number(MARK_PATHS[key].replace("M", "").split(" ")[0])
    )
    expect(startX).toEqual([10.86, 11.1, 11.34])
  })

  it("uses the spec viewBox and stroke width", () => {
    expect(MARK_VIEWBOX).toBe("0 0 64 64")
    expect(MARK_STROKE_WIDTH).toBe(3.5)
  })
})

describe("brand palettes", () => {
  it("defines exactly three contexts", () => {
    expect(Object.keys(MARK_PALETTES).sort()).toEqual(["app", "landing", "onDark"])
  })

  it("gives every context exactly three values and no gradient", () => {
    for (const [name, palette] of Object.entries(MARK_PALETTES)) {
      const values = Object.values(palette)
      expect(values, name).toHaveLength(3)
      expect(new Set(values).size, name).toBe(3)
      for (const value of values) {
        expect(value, name).toMatch(/^#[0-9A-F]{6}$/)
      }
    }
  })

  it("matches the fills table in docs/design/brand.md", () => {
    expect(MARK_PALETTES.app).toEqual({ A: "#B5ADA5", B: "#6B5F57", C: "#1E1915" })
    expect(MARK_PALETTES.landing).toEqual({ A: "#B5ADA5", B: "#A87531", C: "#1E1915" })
    expect(MARK_PALETTES.onDark).toEqual({ A: "#6B5F57", B: "#B5ADA5", C: "#F5F3EF" })
  })
})

describe("small-size degradation", () => {
  it("drops path A below 20px and never scales three blades under it", () => {
    expect(bladesForSize(16)).toEqual(["B", "C"])
    expect(bladesForSize(19.9)).toEqual(["B", "C"])
    expect(bladesForSize(20)).toEqual(["A", "B", "C"])
    expect(bladesForSize(34)).toEqual(["A", "B", "C"])
  })
})

describe("wordmark", () => {
  it("tightens tracking at 30px and above", () => {
    expect(wordmarkTracking(17)).toBe("-0.01em")
    expect(wordmarkTracking(26)).toBe("-0.01em")
    expect(wordmarkTracking(30)).toBe("-0.02em")
    expect(wordmarkTracking(34)).toBe("-0.02em")
  })
})

/**
 * The static files in `public/brand/` are generated by
 * `scripts/generate-brand-assets.mjs`. If the runtime geometry moves and the
 * files are not regenerated, the product and the downloadable assets disagree.
 */
describe("generated brand assets stay in sync with the runtime geometry", () => {
  const threeBladeAssets = [
    ["mark-app.svg", MARK_PALETTES.app],
    ["mark-landing.svg", MARK_PALETTES.landing],
    ["mark-on-dark.svg", MARK_PALETTES.onDark]
  ] as const

  it.each(threeBladeAssets)("%s carries all three blades with its palette", (name, palette) => {
    const svg = readBrandAsset(name)
    expect(svg).toContain(`viewBox="${MARK_VIEWBOX}"`)
    for (const blade of ["A", "B", "C"] as const) {
      expect(svg).toContain(MARK_PATHS[blade])
      expect(svg).toContain(`fill="${palette[blade]}" stroke="${palette[blade]}"`)
    }
    expect(svg).toContain(`stroke-width="${MARK_STROKE_WIDTH}"`)
    expect(svg).not.toContain("linearGradient")
  })

  it("mark-small-20.svg carries only the two lower blades", () => {
    const svg = readBrandAsset("mark-small-20.svg")
    expect(svg).not.toContain(MARK_PATHS.A)
    expect(svg).toContain(MARK_PATHS.B)
    expect(svg).toContain(MARK_PATHS.C)
  })

  it("favicon.svg is the two-blade mark on the ink tile", () => {
    const svg = readBrandAsset("favicon.svg")
    expect(svg).toContain('fill="#1E1915"')
    expect(svg).not.toContain(MARK_PATHS.A)
    expect(svg).toContain(MARK_PATHS.C)
  })

  it("lockup-horizontal.svg sets the wordmark in Geist 500", () => {
    const svg = readBrandAsset("lockup-horizontal.svg")
    expect(svg).toContain("Artifact Studio")
    expect(svg).toContain('font-weight="500"')
    expect(svg).toMatch(/font-family="Geist/)
    expect(svg).toContain('letter-spacing="-0.01em"')
  })

  it("the legacy public/odessay-logo.svg path serves the new mark", () => {
    const svg = readFileSync(join(root, "public/odessay-logo.svg"), "utf8")
    expect(svg).toContain(MARK_PATHS.C)
    expect(svg).not.toContain("linearGradient")
  })
})
