/** @vitest-environment happy-dom */
/**
 * Drift gate for the catalog seam fixture (ODE-613, vía a; ODE-644 PR2).
 *
 * The fixture committed at tests/fixtures/catalog-seam/catalog-seam-v4.json is
 * generated by driving the REAL TS production code (SqliteDocumentCatalog and
 * the WorkspaceReconciler, wired like desktop-workspace-reconciler.ts; and, for
 * SYNC-05, DesktopDocumentService.saveWriting + desktopCatalogSyncService
 * .flushPending) through the mocked Tauri IPC. This test regenerates the
 * sequence from that code and fails if it no longer matches the committed
 * fixture, so the Rust replay can never test a stale sequence. Every invoke
 * step also carries a projection of the double's response, and the SYNC-05
 * scenarios carry control steps; the Rust replay (catalog_seam.rs) asserts the
 * real Rust response and the canonical SQLite state match step by step
 * (P2-1 fix, ODE-613; Req 4-5, ODE-644 PR2).
 *
 * Regenerate with:
 *   UPDATE_CATALOG_SEAM_FIXTURE=1 npx vitest run tests/catalog-seam-fixture.test.ts
 */
import { readFile, writeFile } from "node:fs/promises"
import { mkdir } from "node:fs/promises"
import { describe, expect, it, vi } from "vitest"

// SYNC-05 entra por producción real: path apunta a los placeholders del
// fixture, el runtime es desktop, Supabase es el fake en memoria y el
// scheduleFlush automático no agenda (mismo montaje que ODE-611).
vi.mock("@tauri-apps/api/path", () => ({
  appConfigDir: async () => "$CONFIG",
  appDataDir: async () => "$ROOT_A",
  join: async (...parts: string[]) =>
    parts.length === 2 && parts[0] === "$CONFIG" && parts[1] === "desktop-index.sqlite3"
      ? "$DB"
      : parts.join("/"),
  dirname: async (path: string) => path.replace(/\/[^/]*$/, ""),
}))

vi.mock("@/lib/services/desktop/runtime-detection", () => ({
  isDesktopRuntime: () => true,
}))

vi.mock("@/lib/supabase/desktop-client", async () => {
  const { fakeSupabaseClient } = await import(
    "./integration/documents/support/fake-supabase-server"
  )
  return { createDesktopClient: () => fakeSupabaseClient }
})

vi.mock("@/lib/sync/sync-service-factory", () => ({
  getSyncService: () => ({ scheduleFlush: async () => ({ data: undefined, error: null }) }),
}))

const tauriCore = vi.hoisted(() => ({
  invoke: undefined as
    | ((cmd: string, args: Record<string, unknown>) => Promise<unknown>)
    | undefined,
}))

vi.mock("@tauri-apps/api/core", () => ({
  invoke: (cmd: string, args: Record<string, unknown>) => {
    if (!tauriCore.invoke) {
      throw new Error("catalog-seam fixture test: invoke called outside a recording session")
    }
    return tauriCore.invoke(cmd, args)
  },
  Resource: class {},
  Channel: class {},
}))

import {
  buildCatalogSeamFixture,
  catalogSeamInvoke,
  serializeCatalogSeamFixture,
} from "./support/catalog-seam-recorder"

const FIXTURE_PATH = "tests/fixtures/catalog-seam/catalog-seam-v4.json"

async function generate(): Promise<string> {
  tauriCore.invoke = catalogSeamInvoke
  try {
    return serializeCatalogSeamFixture(await buildCatalogSeamFixture())
  } finally {
    tauriCore.invoke = undefined
  }
}

describe("catalog seam fixture (ODE-613, ODE-637, ODE-644 PR2)", () => {
  it("matches the committed recording of the real wrapper sequence", async () => {
    const generated = await generate()

    if (process.env.UPDATE_CATALOG_SEAM_FIXTURE === "1") {
      await mkdir(FIXTURE_PATH.substring(0, FIXTURE_PATH.lastIndexOf("/")), { recursive: true })
      await writeFile(FIXTURE_PATH, generated, "utf8")
      return
    }

    const committed = await readFile(FIXTURE_PATH, "utf8")
    expect(
      generated,
      "The catalog seam fixture is stale: the TS wrapper/reconciler now emits a different " +
        "invoke sequence. Regenerate with UPDATE_CATALOG_SEAM_FIXTURE=1 and review the diff.",
    ).toBe(committed)
  })

  it("records the commands SYS-01/SYS-05/WATCH-07/SYNC-05 depend on, from production code only", async () => {
    const fixture = JSON.parse(await generate()) as {
      version: number
      scenarios: {
        name: string
        steps: { kind: string; cmd?: string; response?: unknown; mutations?: unknown[] }[]
      }[]
    }

    expect(fixture.version).toBe(4)
    expect(fixture.scenarios.map((scenario) => scenario.name).sort()).toEqual([
      "sync05-save-during-flush-failure",
      "sync05-save-during-flush-success",
      "sys01-homonyms-distinct-roots",
      "sys01-register-move-reopen",
      "sys05-reconcile-tracks-disk",
      "watch04-external-move-across-roots",
      "watch07-external-edit-same-path",
    ])

    const commands = new Set(
      fixture.scenarios.flatMap((scenario) =>
        scenario.steps.flatMap((step) => (step.kind === "invoke" && step.cmd ? [step.cmd] : [])),
      ),
    )
    expect([...commands].sort()).toEqual([
      "catalog_apply_cloud_snapshots",
      "catalog_apply_reconcile",
      "catalog_dual_write",
      "catalog_get_by_id",
      "catalog_list_binding_root_documents",
      "catalog_list_pending_metadata_mutations",
      "catalog_list_pending_mutations",
      "catalog_resolve_path",
      "catalog_update_mutation_status",
      "open_file",
      "workspace_sync",
      "workspace_touch_file",
      "write_file",
    ])

    // Closed-loop recording (P2-1): the Rust replay compares the real
    // response against this projection, so every invoke must carry one.
    const invokes = fixture.scenarios.flatMap((scenario) =>
      scenario.steps.filter((step) => step.kind === "invoke"),
    )
    expect(invokes.length).toBeGreaterThan(0)
    for (const step of invokes) {
      expect(step, `invoke ${step.cmd} is missing its recorded response projection`).toHaveProperty(
        "response",
      )
    }

    // Req 4: el listado de mutaciones proyecta los campos que deciden la cola
    // (payloadJson queda fuera: es eco del argumento ya grabado).
    const mutationListings = fixture.scenarios.flatMap((scenario) =>
      scenario.steps.filter((step) => step.cmd === "catalog_list_pending_mutations"),
    )
    expect(mutationListings.length).toBeGreaterThan(0)
    for (const step of mutationListings) {
      expect(Array.isArray(step.response)).toBe(true)
      for (const row of step.response as Record<string, unknown>[]) {
        expect(Object.keys(row).sort()).toEqual([
          "attemptCount",
          "createdAt",
          "documentId",
          "id",
          "lastError",
          "nextRetryAt",
          "operation",
          "status",
        ])
      }
    }

    // Req 5: cada escena de SYNC-05 cierra con controles de estado canónico
    // (documento + cola) que el replay contrasta en SQLite real.
    for (const name of ["sync05-save-during-flush-failure", "sync05-save-during-flush-success"]) {
      const scenario = fixture.scenarios.find((candidate) => candidate.name === name)
      expect(scenario).toBeDefined()
      const controls = scenario!.steps.filter((step) => step.kind === "control")
      expect(controls.length).toBe(2)
      for (const control of controls) {
        expect(control).toHaveProperty("document.syncStatus")
        expect(control).toHaveProperty("document.cloudPresent")
        expect(control.mutations!.length).toBeGreaterThan(0)
      }
    }

    const watch07 = fixture.scenarios.find((scenario) => scenario.name === "watch07-external-edit-same-path")
    expect(watch07).toBeDefined()
    const syncSteps = watch07!.steps.filter((step) => step.kind === "invoke" && step.cmd === "workspace_sync")
    const syncResponses = syncSteps.map((step) =>
      step.response as { files: { relativePath: string; contentHash: string }[] },
    )
    const watchedHashes = syncResponses
      .map((response) => response.files.find((file) => file.relativePath === "notes/watched.md")?.contentHash)
      .filter((contentHash): contentHash is string => typeof contentHash === "string")
    expect(watchedHashes).toHaveLength(2)
    expect(watchedHashes[0]).toMatch(/^blake3:[0-9a-f]{64}$/)
    expect(watchedHashes[1]).toMatch(/^blake3:[0-9a-f]{64}$/)
    expect(watchedHashes[1]).not.toBe(watchedHashes[0])

    const finalRead = watch07!.steps
      .filter((step) => step.kind === "invoke" && step.cmd === "catalog_get_by_id")
      .at(-1)
    expect(finalRead?.response).toHaveProperty("contentHash", watchedHashes[1])
  })
})
