/** @vitest-environment happy-dom */
/**
 * Drift gate for the catalog seam fixture (ODE-613, vía a; ODE-644 PR2).
 *
 * The fixture committed at tests/fixtures/catalog-seam/catalog-seam-v4.json is
 * generated by driving the REAL TS production code (SqliteDocumentCatalog and
 * the WorkspaceReconciler, whose scan/bind/commit ports come from the same
 * injectable factory production consumes, workspace-reconciler-ports.ts; and,
 * for SYNC-05, DesktopDocumentService.saveWriting + desktopCatalogSyncService
 * .flushPending) through the mocked Tauri IPC. This test regenerates the
 * sequence from that code and fails if it no longer matches the committed
 * fixture, so the Rust replay can never test a stale sequence (STALE_PROOF).
 * Every invoke
 * step also carries a projection of the double's response, and the SYNC-05
 * scenarios carry control steps; the Rust replay (catalog_seam.rs) asserts the
 * real Rust response and the canonical SQLite state match step by step
 * (P2-1 fix, ODE-613; Req 4-5, ODE-644 PR2).
 *
 * Regenerate with:
 *   UPDATE_CATALOG_SEAM_FIXTURE=1 npx vitest run tests/catalog-seam-fixture.test.ts
 */
import { readFile, writeFile } from "node:fs/promises"
import { mkdir } from "node:fs/promises"
import { describe, expect, it, vi } from "vitest"

// SYNC-05 entra por producción real: path apunta a los placeholders del
// fixture, el runtime es desktop, Supabase es el fake en memoria y el
// scheduleFlush automático no agenda (mismo montaje que ODE-611).
vi.mock("@tauri-apps/api/path", () => ({
  appConfigDir: async () => "$CONFIG",
  appDataDir: async () => "$ROOT_A",
  join: async (...parts: string[]) =>
    parts.length === 2 && parts[0] === "$CONFIG" && parts[1] === "desktop-index.sqlite3"
      ? "$DB"
      : parts.join("/"),
  dirname: async (path: string) => path.replace(/\/[^/]*$/, ""),
}))

vi.mock("@/lib/services/desktop/runtime-detection", () => ({
  isDesktopRuntime: () => true,
}))

vi.mock("@/lib/supabase/desktop-client", async () => {
  const { fakeSupabaseClient } = await import(
    "./integration/documents/support/fake-supabase-server"
  )
  return { createDesktopClient: () => fakeSupabaseClient }
})

vi.mock("@/lib/sync/sync-service-factory", () => ({
  getSyncService: () => ({ scheduleFlush: async () => ({ data: undefined, error: null }) }),
}))

const tauriCore = vi.hoisted(() => ({
  invoke: undefined as
    | ((cmd: string, args: Record<string, unknown>) => Promise<unknown>)
    | undefined,
}))

vi.mock("@tauri-apps/api/core", () => ({
  invoke: (cmd: string, args: Record<string, unknown>) => {
    if (!tauriCore.invoke) {
      throw new Error("catalog-seam fixture test: invoke called outside a recording session")
    }
    return tauriCore.invoke(cmd, args)
  },
  Resource: class {},
  Channel: class {},
}))

import {
  buildCatalogSeamFixture,
  catalogSeamInvoke,
  serializeCatalogSeamFixture,
} from "./support/catalog-seam-recorder"

const FIXTURE_PATH = "tests/fixtures/catalog-seam/catalog-seam-v4.json"

async function generate(): Promise<string> {
  tauriCore.invoke = catalogSeamInvoke
  try {
    return serializeCatalogSeamFixture(await buildCatalogSeamFixture())
  } finally {
    tauriCore.invoke = undefined
  }
}

describe("catalog seam fixture (ODE-613, ODE-637, ODE-644 PR2)", () => {
  it("matches the committed recording of the real wrapper sequence", async () => {
    const generated = await generate()

    if (process.env.UPDATE_CATALOG_SEAM_FIXTURE === "1") {
      await mkdir(FIXTURE_PATH.substring(0, FIXTURE_PATH.lastIndexOf("/")), { recursive: true })
      await writeFile(FIXTURE_PATH, generated, "utf8")
      return
    }

    const committed = await readFile(FIXTURE_PATH, "utf8")
    expect(
      generated,
      "The catalog seam fixture is stale: the TS wrapper/reconciler now emits a different " +
        "invoke sequence. Regenerate with UPDATE_CATALOG_SEAM_FIXTURE=1 and review the diff.",
    ).toBe(committed)
  })

  it("records the commands SYS-01/SYS-05/WATCH-07/SYNC-05/SYNC-08 depend on, from production code only", async () => {
    const fixture = JSON.parse(await generate()) as {
      version: number
      scenarios: {
        name: string
        steps: {
          kind: string
          name?: string
          cmd?: string
          args?: Record<string, unknown>
          response?: unknown
          mutations?: unknown[]
        }[]
      }[]
    }

    expect(fixture.version).toBe(4)
    expect(fixture.scenarios.map((scenario) => scenario.name).sort()).toEqual([
      "sync05-save-during-flush-failure",
      "sync05-save-during-flush-success",
      "sync05-workspace-removal-not-exists",
      "sync08-bound-pending-save-metadata",
      "sync08-first-upload-metadata-before-flush",
      "sync08-settings-metadata-batch",
      "sys01-homonyms-distinct-roots",
      "sys01-register-move-reopen",
      "sys05-reconcile-tracks-disk",
      "watch04-external-move-across-roots",
      "watch07-external-edit-same-path",
    ])

    const commands = new Set(
      fixture.scenarios.flatMap((scenario) =>
        scenario.steps.flatMap((step) => (step.kind === "invoke" && step.cmd ? [step.cmd] : [])),
      ),
    )
    expect([...commands].sort()).toEqual([
      "catalog_activate_binding_root",
      "catalog_apply_cloud_snapshots",
      "catalog_apply_reconcile",
      "catalog_apply_workspace_removal",
      "catalog_bulk_dual_write",
      "catalog_dual_write",
      "catalog_get_by_id",
      "catalog_list",
      "catalog_list_binding_root_documents",
      "catalog_list_pending_metadata_mutations",
      "catalog_list_pending_mutations",
      "catalog_resolve_path",
      "catalog_update_mutation_status",
      "open_file",
      "settings_read",
      "settings_write",
      "workspace_sync",
      "workspace_touch_file",
      "write_file",
    ])

    // Closed-loop recording (P2-1): the Rust replay compares the real
    // response against this projection, so every invoke must carry one.
    const invokes = fixture.scenarios.flatMap((scenario) =>
      scenario.steps.filter((step) => step.kind === "invoke"),
    )
    expect(invokes.length).toBeGreaterThan(0)
    for (const step of invokes) {
      expect(step, `invoke ${step.cmd} is missing its recorded response projection`).toHaveProperty(
        "response",
      )
    }

    // Req 4: el listado de mutaciones proyecta los campos que deciden la cola
    // (payloadJson queda fuera: es eco del argumento ya grabado).
    const mutationListings = fixture.scenarios.flatMap((scenario) =>
      scenario.steps.filter((step) => step.cmd === "catalog_list_pending_mutations"),
    )
    expect(mutationListings.length).toBeGreaterThan(0)
    for (const step of mutationListings) {
      expect(Array.isArray(step.response)).toBe(true)
      for (const row of step.response as Record<string, unknown>[]) {
        expect(Object.keys(row).sort()).toEqual([
          "attemptCount",
          "createdAt",
          "documentId",
          "id",
          "lastError",
          "nextRetryAt",
          "operation",
          "status",
        ])
      }
    }

    // Req 5: cada escena de SYNC-05 cierra con controles de estado canónico
    // (documento + cola) que el replay contrasta en SQLite real.
    for (const name of [
      "sync05-save-during-flush-failure",
      "sync05-save-during-flush-success",
      "sync05-workspace-removal-not-exists",
    ]) {
      const scenario = fixture.scenarios.find((candidate) => candidate.name === name)
      expect(scenario).toBeDefined()
      const controls = scenario!.steps.filter((step) => step.kind === "control")
      expect(controls.length).toBe(2)
      for (const control of controls) {
        expect(control).toHaveProperty("document.syncStatus")
        expect(control).toHaveProperty("document.cloudPresent")
        expect(control.mutations!.length).toBeGreaterThan(0)
      }
    }

    // ODE-663: la escena del retiro llega a la rama `NOT EXISTS` por la
    // secuencia real — `catalog_apply_workspace_removal` retira la raíz y encola
    // el delete del documento cloud-owned. El id que Rust acuña (index.rs:957)
    // se graba con alias estable, nunca literal; el resto de la fila se
    // compara en los controles (estado, retry, payload, orden, documentId).
    const removal = fixture.scenarios.find(
      (scenario) => scenario.name === "sync05-workspace-removal-not-exists",
    )
    const removalInvocations = removal!.steps.filter(
      (step) => step.kind === "invoke" && step.cmd === "catalog_apply_workspace_removal",
    )
    expect(removalInvocations).toHaveLength(1)
    expect(removalInvocations[0]!.args).toEqual(
      expect.objectContaining({
        bindingRootId: "fixture-root-a",
        rootPath: "$ROOT_A",
      }),
    )
    const removalControls = removal!.steps.filter((step) => step.kind === "control") as unknown as {
      name: string
      documentId: string
      mutations: { id: string; status: string }[]
    }[]
    expect(removalControls.map((control) => control.name)).toEqual([
      "sync05-removal-not-exists-guard",
      "sync05-removal-delete-resolved",
    ])
    expect(removalInvocations[0]!.response).toEqual([removalControls[0]!.documentId])
    expect(removalControls[0]!.mutations.map((mutation) => mutation.status)).toEqual([
      "synced",
      "pending",
    ])
    expect(removalControls[1]!.mutations.map((mutation) => mutation.status)).toEqual([
      "synced",
      "synced",
    ])
    const generatedId = removalControls[0]!.mutations[1]!.id
    expect(generatedId.startsWith("$MUTATION_")).toBe(true)
    expect(removalControls[1]!.mutations[1]!.id).toBe(generatedId)
    expect(
      removal!.steps.filter(
        (step) => step.kind === "invoke" && step.cmd === "catalog_activate_binding_root",
      ),
    ).toHaveLength(1)

    const watch07 = fixture.scenarios.find((scenario) => scenario.name === "watch07-external-edit-same-path")
    expect(watch07).toBeDefined()
    const syncSteps = watch07!.steps.filter((step) => step.kind === "invoke" && step.cmd === "workspace_sync")
    const syncResponses = syncSteps.map((step) =>
      step.response as { files: { relativePath: string; contentHash: string }[] },
    )
    const watchedHashes = syncResponses
      .map((response) => response.files.find((file) => file.relativePath === "notes/watched.md")?.contentHash)
      .filter((contentHash): contentHash is string => typeof contentHash === "string")
    expect(watchedHashes).toHaveLength(2)
    expect(watchedHashes[0]).toMatch(/^blake3:[0-9a-f]{64}$/)
    expect(watchedHashes[1]).toMatch(/^blake3:[0-9a-f]{64}$/)
    expect(watchedHashes[1]).not.toBe(watchedHashes[0])

    const finalRead = watch07!.steps
      .filter((step) => step.kind === "invoke" && step.cmd === "catalog_get_by_id")
      .at(-1)
    expect(finalRead?.response).toHaveProperty("contentHash", watchedHashes[1])

    // ODE-670: el contrato de `catalog_bulk_dual_write` es "ids escritos, en
    // orden de entrada"; invertir el orden debe romper el replay.
    const bulkWrites = fixture.scenarios.flatMap((scenario) =>
      scenario.steps.filter((step) => step.kind === "invoke" && step.cmd === "catalog_bulk_dual_write"),
    )
    expect(bulkWrites.length).toBeGreaterThan(0)
    for (const step of bulkWrites) {
      const inputs = step.args!.inputs as { document: { id: string } }[]
      expect(step.response).toEqual(inputs.map((input) => input.document.id))
    }

    // ODE-670: el camino de Settings pasa la query real del productor
    // (`cloudAccountId:null`) y el catálogo real excluye la fila solo-nube con
    // cuenta (filtro de cuenta del SQL); el replay contrasta esa misma lista.
    const settingsScenario = fixture.scenarios.find(
      (scenario) => scenario.name === "sync08-settings-metadata-batch",
    )
    expect(settingsScenario).toBeDefined()
    const listStep = settingsScenario!.steps.find(
      (step) => step.kind === "invoke" && step.cmd === "catalog_list",
    )
    expect(listStep).toBeDefined()
    expect(listStep!.args).toEqual({
      dbPath: "$DB",
      cloudAccountId: null,
      includeDeleted: false,
      localOnly: false,
      limit: 100000,
    })
    const listedIds = (listStep!.response as { id: string }[]).map((row) => row.id)
    const cloudOnlyControl = settingsScenario!.steps.find(
      (step) =>
        step.kind === "control" &&
        (step as { name?: string }).name === "sync08-settings-cloud-only-excluded",
    ) as { documentId: string } | undefined
    expect(cloudOnlyControl).toBeDefined()
    expect(listedIds).not.toContain(cloudOnlyControl!.documentId)
    expect(listedIds).toHaveLength(2)

    // ODE-670: cada escenario SYNC-08 afirma el payload que distingue una
    // mutación de metadata real de una de cuerpo, y los controles de Settings
    // separan la fila cloud-owned, el control local-only y la fila excluida.
    for (const name of [
      "sync08-bound-pending-save-metadata",
      "sync08-first-upload-metadata-before-flush",
    ]) {
      const scenario = fixture.scenarios.find((candidate) => candidate.name === name)
      expect(scenario).toBeDefined()
      const controls = scenario!.steps.filter((step) => step.kind === "control") as {
        mutations: { status: string; payload?: { mutationKind: string | null } }[]
      }[]
      const actionableMetadata = controls.flatMap((control) =>
        control.mutations.filter(
          (mutation) => mutation.status === "pending" && mutation.payload?.mutationKind === "metadata",
        ),
      )
      const supersededBody = controls.flatMap((control) =>
        control.mutations.filter(
          (mutation) => mutation.status === "synced" && mutation.payload?.mutationKind === null,
        ),
      )
      expect(actionableMetadata).toHaveLength(1)
      expect(supersededBody).toHaveLength(1)
    }
    const settingsControls = settingsScenario!.steps.filter((step) => step.kind === "control") as {
      name: string
      mutations: { status: string; payload?: { mutationKind: string | null } }[]
    }[]
    expect(
      settingsControls.find((control) => control.name === "sync08-settings-cloud-owned-rewritten")!.mutations,
    ).toEqual([
      expect.objectContaining({
        status: "pending",
        payload: expect.objectContaining({ mutationKind: "metadata" }),
      }),
    ])
    expect(
      settingsControls.find((control) => control.name === "sync08-settings-local-only-control")!.mutations,
    ).toEqual([])
    expect(
      settingsControls.find((control) => control.name === "sync08-settings-cloud-only-excluded")!.mutations,
    ).toEqual([])
  })
})

/**
 * Follow-up pendiente (ODE-670): el productor de Settings pasa
 * `cloudAccountId:null` a `catalog_list` (desktop-settings-service.ts:446) y el
 * SQL real trata null como "sin cuenta activa", así que una fila solo-nube con
 * cuenta nunca entra al lote y no recibe la reescritura. ODE-648 no lo vio
 * porque su doble (`tauriCatalogListDouble`, real-desktop-doubles.ts:1130)
 * ignora la query. Este `it.fails` fija la conducta correcta: cuando el
 * productor pase la cuenta activa, el lote debe incluir la fila solo-nube; al
 * arreglarlo, este test pasa y el `it.fails` se convierte en `it`.
 */
it.fails(
  "follow-up pendiente (ODE-670): Settings debe reescribir también la fila solo-nube con cuenta",
  async () => {
    const fixture = JSON.parse(await generate()) as {
      scenarios: {
        name: string
        steps: {
          kind: string
          name?: string
          cmd?: string
          args?: Record<string, unknown>
          documentId?: string
        }[]
      }[]
    }
    const scenario = fixture.scenarios.find(
      (candidate) => candidate.name === "sync08-settings-metadata-batch",
    )!
    const cloudOnly = scenario.steps.find(
      (step) => step.kind === "control" && step.name === "sync08-settings-cloud-only-excluded",
    )!
    const bulkIds = scenario.steps
      .filter((step) => step.kind === "invoke" && step.cmd === "catalog_bulk_dual_write")
      .flatMap((step) =>
        (step.args!.inputs as { document: { id: string } }[]).map((input) => input.document.id),
      )
    expect(bulkIds).toContain(cloudOnly.documentId)
  },
)
